# Game Rules

# 1. Take turns to solve math questions
# 2. new questions are generated by picking two numbers between 1 and 20
# 3. the player whose turn it is must answer or lose a life
# 4. Both players start with 3 lives, if they lose a life
# 5. the game doesnt end until one user loses all their lives


# Tech Requirements
# 1. Text input


# Class Requirements
# Player
# -intialize name, lives-
# -use accessor to set/get names


# Questions
# -choose random numbers between 0-20
# -ask waht is the sum of these numbers

# Game
# -initialize and define player nmaes
# -switch betweeen player turns
# -determine how the game ends
# -define win condition
# -play the game

require 'byebug'

class Player
  attr_accessor :name, :lives

  def initialize(name)
    @name = name
    @lives = 3
  end
    
end

class Question

  def generate_question
    number1 = rand(1..20)
    number2 = rand(1..20)
    answer = number1 + number2
    puts "What does #{number1} + #{number2} equal"
    answer
  end

end


class Game

  attr_accessor :player1

  def initialize
    @player1 = Player.new("Player 1")
    @player2 = Player.new("player 2")
    @current_player = @player1
    @question = Question.new
  end


  def game_over?
    @player1.lives == 0 || @player2.lives == 0
  end

  def switch_player
    #if the switch
    if @current_player == @player1
      @current_player = @player2
    else
      @current_player = @player1
    end
  end

  def play
    # byebug
    until game_over?
      puts "it is your turn now #{@current_player.name}"
      answer = @question.generate_question
      # puts "answer #{answer}"
      player_answer = gets.chomp.to_i
      if player_answer != answer
        @current_player.lives -= 1
        puts "Incorrect #{@current_player.name}. You have #{@current_player.lives} lives left."
      else
        puts "Correct #{@current_player.name}. You have #{@current_player.lives} lives left."
      end
      switch_player
    end
    puts "Congrats #{@current_player.name}! You win"
  end
end


game = Game.new
game.play